package com.feitai.admin.system.model;

// Generated 2014-8-26 14:05:09 by Hibernate Tools 3.2.2.GA


import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DictionaryType generated by hbm2java
 */
@Table(name = "sys_dictionary_type")
@Data
public class DictionaryType  {

	@Id
	protected Long id;

	private String name;

	private String code;

	private String memo;

}
