package com.feitai.admin.system.model;

// Generated 2014-6-19 17:10:12 by Hibernate Tools 3.4.0.CR1

import com.alibaba.fastjson.annotation.JSONField;
import com.feitai.admin.system.mapper.ResourceMapper;
import com.feitai.base.mybatis.Many;
import com.feitai.base.mybatis.One;
import lombok.Data;
import tk.mybatis.mapper.annotation.KeySql;

import javax.persistence.Id;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.List;

/**
 * Resource generated by hbm2java
 */
@Table(name = "sys_resource")
@Data
public class Resource{

	@Id
	@KeySql(useGeneratedKeys = true)
	protected Long id;

	@Transient
	@One(classOfMapper = ResourceMapper.class, sourceField = "parentId")
	private Resource parent;

	private String parentId;

	private String name;

	private String code;

	private String url;

	private String ico;

	private Integer isRoot;

	private Integer isShow;

	private Integer orderId;

	private Integer level;

	private String parentIds;

	private String permissionIds;

	private String memo;

	@Transient
	@Many(classOfMapper = ResourceMapper.class, classOfEntity = Resource.class, targetField = "parentId")
	@OrderBy("order_id ASC")
	@JSONField(serialize = false)
	private List<Resource> resources;


}
