package com.feitai.admin.system.model;

// Generated 2014-6-19 17:10:12 by Hibernate Tools 3.4.0.CR1

import com.feitai.admin.system.mapper.RoleAuthMapper;
import com.feitai.base.mybatis.Many;
import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;
import java.util.List;

/**
 * Role generated by hbm2java
 */
@Table(name = "sys_role")
@Data
public class Role {

	@Id
	private Long id;

	private String name;

	private String code;

	private String memo;

	private Date createTime;

	@Transient
	@Many(classOfMapper = RoleAuthMapper.class, classOfEntity = RoleAuth.class, targetField = "roleId")
	private List<RoleAuth> roleAuths;

}
