package com.feitai.admin.system.model;

// Generated 2014-6-19 17:10:12 by Hibernate Tools 3.4.0.CR1

import com.alibaba.fastjson.annotation.JSONField;
import com.feitai.admin.system.mapper.SysUserMapper;
import com.feitai.base.mybatis.One;
import lombok.Data;
import tk.mybatis.mapper.annotation.KeySql;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * User generated by hbm2java
 */
@Table(name = "sys_user")
@Data
public class User {

	@Id
	@KeySql(useGeneratedKeys = true)
	private Long id;

	private Long createrId;

	@Transient
	@One(classOfMapper = SysUserMapper.class, sourceField = "createrId")
	private User creater;

	private String loginName;

	@JSONField(serialize = false)
	private String password;

	@JSONField(serialize = false)
	private String salt;

	private String name;

	private String email;

	private Date createTime;

	private Short status;

	private Date lastLoginTime;

	private String lastLoginIp;

	@Transient
	private List<Role> roles = new ArrayList<Role>(0);

	@Transient
	// 从界面传过来的密码，非数据库字段
	@JSONField(serialize = false)
	private String plainPassword;

	public User(Long id, String loginName, String password) {
		this.id = id;
		this.loginName = loginName;
		this.password = password;
	}

	public User(){
	}
}
